# Supabase Configuration
SUPABASE_URL = "https://soeuzisxnpgahjrmwvir.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvZXV6aXN4bnBnYWhqcm13dmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODQ0OTksImV4cCI6MjA3MTM2MDQ5OX0.TtFANb2pRQDhYI4gfZJDt9cBi_zMwVXRpZmUtrZuD1g"

# Google API Key
GOOGLE_API_KEY = "AIzaSyAffz2pEZbW7kQi1oo3mH74VZjgpi52yaI" 