# ⚠️ GÜVENLİK UYARISI: Bu dosyayı asla public repository'ye commit etmeyin!
# Gerçek değerleri sadece local development ve production ortamında kullanın.

# Supabase Configuration
SUPABASE_URL = "YOUR_SUPABASE_URL_HERE"
SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY_HERE"

# Google API Key
GOOGLE_API_KEY = "YOUR_GOOGLE_API_KEY_HERE" 